version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of build.gradle files
    schedule:
      interval: "daily" # How often to check for updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"